name: Update AdoptOpenJDK

on:
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for AdoptOpenJDK"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-lein-
      - name: Set up ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run adoptopenjdk
        run: lein run -m sdkman-java-migrations.adoptopenjdk
