name: Update GraalVM

on:
  schedule:
      - cron: 0 5 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for GraalVM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-lein-
      - name: Set up ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run graalvm
        run: lein run -m sdkman-java-migrations.graalvm
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
