name: Update SapMachine

on:
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for SapMachine"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-lein-
      - run: |
          curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/2.9.5/bin/lein
          chmod +x lein
      - name: Set up ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run sap-machine
        run: lein run -m sdkman-java-migrations.sap-machine
