name: Update Alibaba Dragonwell

on:
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for Alibaba Dragonwell"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-lein-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-lein-
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run alibaba-dragonwell
        run: lein run -m sdkman-java-migrations.alibaba-dragonwell
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
